version: "3"
services:

  mysql:
    build: "./MYSQL/"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: eke_mysql
      MYSQL_DATABASE: eke
    ports:
      - "3308:3306"

  node:
    build: "./NODEJS/"
    volumes:
      - "./NODEJS/:/home/node/app/"
    restart: "unless-stopped"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: eke_mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: eke
      WAIT_HOSTS: mysql:3306
    ports:
      - "8080:8080"
